create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade
);

create table if not exists public.products (
  id bigint primary key generated by default as identity,
  name text not null,
  description text not null,
  price numeric not null check (price >= 0),
  category text not null,
  image text not null,
  featured boolean not null default false
);

alter table public.admin_users enable row level security;
alter table public.products enable row level security;

drop policy if exists "Public can read products" on public.products;
drop policy if exists "Admins can read admin list" on public.admin_users;
drop policy if exists "Admins can insert products" on public.products;
drop policy if exists "Admins can update products" on public.products;
drop policy if exists "Admins can delete products" on public.products;

create policy "Public can read products" on public.products
  for select using (true);

create policy "Admins can read admin list" on public.admin_users
  for select to authenticated
  using (user_id = auth.uid());

create policy "Admins can insert products" on public.products
  for insert to authenticated
  with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Admins can update products" on public.products
  for update to authenticated
  using (exists (select 1 from public.admin_users where user_id = auth.uid()))
  with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Admins can delete products" on public.products
  for delete to authenticated
  using (exists (select 1 from public.admin_users where user_id = auth.uid()));