create table if not exists public.admin_users (
  email text primary key,
  name text not null,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.auth_sessions (
  token_hash text primary key,
  admin_email text not null references public.admin_users(email) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists auth_sessions_expires_at_idx on public.auth_sessions (expires_at);

create table if not exists public.categories (
  name text primary key,
  image text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint primary key generated by default as identity,
  name text not null,
  description text not null,
  price numeric not null check (price >= 0),
  category text not null,
  image text not null,
  featured boolean not null default false,
  sold_out boolean not null default false,
  stock_quantity integer not null default 0 check (stock_quantity >= 0)
);

alter table public.admin_users enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;

drop policy if exists "Public can read products" on public.products;
drop policy if exists "Public can read categories" on public.categories;
drop policy if exists "Admins can read admin list" on public.admin_users;
drop policy if exists "Admins can insert products" on public.products;
drop policy if exists "Admins can update products" on public.products;
drop policy if exists "Admins can delete products" on public.products;
drop policy if exists "Admins can insert categories" on public.categories;
drop policy if exists "Admins can update categories" on public.categories;
drop policy if exists "Admins can delete categories" on public.categories;

create policy "Public can read products" on public.products
  for select using (true);

create policy "Public can read categories" on public.categories
  for select using (true);

create policy "Admins can read admin list" on public.admin_users
  for select to authenticated
  using (user_id = auth.uid());

create policy "Admins can insert products" on public.products
  for insert to authenticated
  with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Admins can update products" on public.products
  for update to authenticated
  using (exists (select 1 from public.admin_users where user_id = auth.uid()))
  with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Admins can delete products" on public.products
  for delete to authenticated
  using (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Admins can insert categories" on public.categories
  for insert to authenticated
  with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Admins can update categories" on public.categories
  for update to authenticated
  using (exists (select 1 from public.admin_users where user_id = auth.uid()))
  with check (exists (select 1 from public.admin_users where user_id = auth.uid()));

create policy "Admins can delete categories" on public.categories
  for delete to authenticated
  using (exists (select 1 from public.admin_users where user_id = auth.uid()));